algoritmo "maior ou igual"
var
   n1 , n2: inteiro
inicio
      escreva("Digite um numero: ")
      leia(n1)
      escreva("DDigite um numero: ")
      leia(n2)
      Se(n1 > n2) entao
            escreval("O Numero maior e ", n1)
      senao
           escreval("O numero maior e ", n2)
      fimse
           se (n1 = n2) entao
              escreval("Os numeros são iguais")
           fimse
fimalgoritmo
